### PR TITLE
Better fonts

### PR DESCRIPTION
**Pull request by ogarcia**
By default Skype fonts are very ugly, this small fix improve fonts in much better look and Docker image only grows around 100 Kb.

### CODE REVIEW

**Comment by ogarcia** [comment]
I add an small update to use date command to get timezone instead make cat to `/etc/timezone`. This is much better cause not all distros have `/etc/timezone` file.

**Comment by sameersbn** [comment]
@ogarcia can you submit a separate PR for the timezone changes?

> this small fix improve fonts in much better look

while you have piqued my interest with this PR, I don't like the font. How about using the "Ubuntu" font family.

`apt-get install -y ttf-ubuntu-font-family` and `font="Ubuntu,10,-1,5,50,0,0,0,0,0"`

**Comment by ogarcia** [comment]
Ok. I do three new PR. One with timezone fix and two with fonts improvement. I think that looks better with Cantarell fonts, but Ubunu fonts fonts don't look bad. The size of font must be 11, set it to 10 is too small.

I close this PR.

**Comment by ogarcia** [comment]
Ah, take note that with Cantarell the image only grows 100 Kb and with ubuntu fonts around 5 Mb.

**Pull request closed without merging**
